### ISSUE TITLE
OPL2 Audio [Issue] 

### ISSUE THREAD

**Issue by real-amano** [va7deo/zerowing#43]
2 weeks ago Jotego found the culprit for this bug in his audio core and fixed it. Just to let you know since it is still mentioned in your readme.md.

See https://github.com/jotego/jtopl/issues/11

**Comment by atrac17** [comment]
> 2 weeks ago Jotego found the culprit for this bug in his audio core and fixed it. Just to let you know since it is still mentioned in your readme.md.
> 
> See https://github.com/jotego/jtopl/issues/11

I'm tracking the commit, we'll see what the outcome gives.

**Comment by atrac17** [comment]
@real-amano here is an updated build, let me know what you think.

[zerowing20240404.zip](https://github.com/va7deo/zerowing/files/14876429/zerowing20240404.zip)

**Comment by sherhacky** [comment]
@atrac17  In case it's helpful, here's a recording of some gameplay of Truxton on the updated build: https://youtu.be/4F8OBvQk-B8
Awesome: Instruments that were previously silent are now booming!
I think there are still balance issues, as many of those same instruments are distorted/crunchy sounding.  Below I'm relying on [Sumez's 1cc YT vid on PCB](https://youtu.be/osDHJ9WKiZk?si=2ZLyIYBe8VJalAmU) as a source of truth.
- zako (+ other) explosions are loud and distorted, often drowning out other music/sound (admittedly I think this is a feature of the game, but sounds more pronounced: compare [new build](https://youtu.be/4F8OBvQk-B8?si=MXp2L2Q2KndIZOiW&t=45) to [recording from PCB](https://youtu.be/osDHJ9WKiZk?si=4ncA-9IB8XJ8tjZX&t=46))
- piercing laser (green) has two sounds that play that differ in tone/volume; [in the new core they are dramatically different](https://youtu.be/4F8OBvQk-B8?si=8XXGZgBg3aS61sJZ&t=110), compared to [audio from PCB](https://youtu.be/osDHJ9WKiZk?si=kVLxubRIGn-mU5s9&t=233)
- 2nd stage background music: [Bass line is distorted](https://youtu.be/4F8OBvQk-B8?si=v8uzjkn4y0OLcuu6&t=317) compared to [PCB audio](https://youtu.be/osDHJ9WKiZk?si=xw1sxqvYd9w-c_bD&t=289)
- Music in high score entry screen has lead voice that is [loud and distorted](https://youtu.be/4F8OBvQk-B8?si=kGRZ3tMpAyZfBWvf&t=573), [not noticeable on PCB](https://youtu.be/osDHJ9WKiZk?si=Yu3pEvuu1X7gaiQr&t=2415)

**Comment by atrac17** [comment]
Thanks, it's be best to report this in https://github.com/jotego/jtopl/issues/11.  It's been reported off of GitHub by me over two years ago and on it by additional users.  I've already tested everything, percussion is present but not correct.  There is no balancing or filtering to be done on the core side (per schematics); the issue lies in the OPL2 implementation.

I own Tatsujin, OutZone, and have measurements / recordings for all PCB's that fall under Toaplan1.  You're more than welcome to address this with the author of the module.  I suggest using OutZone as a reference, it's easiest to pinpoint that there are still percussion samples missing or they're too quiet.

I'm already in the process of updating all the cores that utilize OPL or OPL2 and verifying improvement.  Thanks for your detailed report.  Below is the best track to verify OPL2 against taken from the OutZone PCB, it should be used for reference against track 02 in the service menu.

https://drive.google.com/file/d/1iQcNg3I362-YyhUKCtfUQ1FB1lqp7hVo/view?usp=sharing
